name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python '3.12.1'
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-xdist  # Instala pytest y pytest-xdist para la ejecución paralela
    - name: Change to parallel directory
      run: cd parallel
    - name: Run tests in parallel directory
      run: pytest -n 2
